set(sources
	src/about_qt.cpp
	src/about_qt.h
	src/about_qt.ui
	src/AudioEffectsDialog.cpp
	src/AudioEffectsDialog.h
	src/buildinfo.c
	src/buildinfo.h
	src/bytebuffer.h
	src/CmdQueue.cpp
	src/CmdQueue.h
	src/common.h
	src/config_qt.cpp
	src/config_qt.h
	src/config_qt.ui
	src/ConfigModel.cpp
	src/ConfigModel.h
	src/ExpandableSection.cpp
	src/ExpandableSection.h
	src/ExpandableSection.ui
	src/HighResClock.cpp
	src/HighResClock.h
	src/inputfile.h
	src/inputfileffmpeg.cpp
	src/main.cpp
	src/main.h
	src/peakmeter.h
	src/plugin.cpp
	src/plugin.h
	src/qtres.qrc
	src/dark_style.qss
	src/style_helper.cpp
	src/style_helper.h
	src/SampleBuffer.cpp
	src/SampleBuffer.h
	src/SampleProducer.h
	src/SampleProducerThread.cpp
	src/SampleProducerThread.h
	src/samples.cpp
	src/samples.h
	src/SampleSource.h
	src/SampleVisualizerThread.cpp
	src/SampleVisualizerThread.h
	src/SoundButton.cpp
	src/SoundButton.h
	src/SoundInfo.cpp
	src/SoundInfo.h
	src/soundsettings_qt.cpp
	src/soundsettings_qt.h
	src/soundsettings_qt.ui
	src/soundview_qt.cpp
	src/soundview_qt.h
	src/SpeechBubble.cpp
	src/SpeechBubble.h
	src/TalkStateManager.cpp
	src/TalkStateManager.h
	src/ts3log.cpp
	src/ts3log.h
	src/UpdateChecker.cpp
	src/UpdateChecker.h
	src/updater.ui
	src/updater_qt.cpp
	src/updater_qt.h
	src/updater_qt.ui

	# --- Modular UI (Phase 2+) ---
	src/modules/module_registry.h
	src/modules/module_registry.cpp
	src/modules/fine_slider.h
	src/modules/fine_slider.cpp
	src/modules/hotkey_block.h
	src/modules/hotkey_block.cpp
	src/modules/volume_control.h
	src/modules/volume_control.cpp
	src/modules/fx_panel.h
	src/modules/fx_panel.cpp
	src/modules/waveform_player.h
	src/modules/waveform_player.cpp
	src/modules/channel.h
	src/modules/channel.cpp
	src/modules/search_bar.h
	src/modules/search_bar.cpp
	src/modules/button_grid.h
	src/modules/button_grid.cpp
	src/modules/button_advanced_panel.h
	src/modules/button_advanced_panel.cpp
	src/modules/settings_window.h
	src/modules/settings_window.cpp
	src/modules/config_io.h
	src/modules/config_io.cpp
	src/modules/reset_channels_btn.h
	src/modules/reset_channels_btn.cpp
	src/modules/channel_state_persistence.h
	src/modules/channel_state_persistence.cpp
	src/modules/help_bubble.h
	src/modules/help_bubble.cpp
	src/modules/theme.h
	src/modules/theme.cpp
	src/modules/main_page.h
	src/modules/main_page.cpp
	src/modules/main_page_wiring.h
	src/modules/main_page_wiring.cpp

	# --- Audio sandbox DSP (per-channel HRTF / paulstretch / EQ / reverb) ---
	src/dsp/SandboxState.h
	src/dsp/SandboxState.cpp
	src/dsp/SlotDsp.h
	src/dsp/SlotDsp.cpp
	src/dsp/BiquadPeaking.h
	src/dsp/BiquadPeaking.cpp
	src/dsp/EqRack.h
	src/dsp/EqRack.cpp
	src/dsp/Positional.h
	src/dsp/Positional.cpp
	src/dsp/Reverb.h
	src/dsp/Reverb.cpp
	src/dsp/Paulstretch.h
	src/dsp/Paulstretch.cpp

	# --- Sandbox per-channel UI ---
	src/modules/channel_meter.h
	src/modules/channel_meter.cpp
	src/modules/channel_sandbox_dialog.h
	src/modules/channel_sandbox_dialog.cpp
	src/modules/positional_pad.h
	src/modules/positional_pad.cpp
)
