#!/usr/bin/env python3
"""
Apply the Italian translation map to soundboard_it.ts.

Each entry in TRANSLATIONS maps an English <source> string (exactly as
it appears in the .ts XML, HTML-escaped) to its Italian rendering.
The script finds every <message> whose <source> is in the map and is
currently marked type="unfinished" and rewrites the <translation>
element with the IT text.

Run with no arguments. Edits the .ts file in place. Idempotent.
"""

from __future__ import annotations

import re
from pathlib import Path

TS_PATH = Path(__file__).resolve().parents[1] / "src" / "i18n" / "soundboard_it.ts"

# All source strings below are stored in XML-escaped form so they
# match the raw bytes in the .ts file. The translation values are
# stored the same way — the file is XML so any literal '<' or '>' has
# to remain escaped.
TRANSLATIONS: dict[str, str] = {
    # --- short labels / button captions ---
    "Clear": "Cancella",
    "Close": "Chiudi",
    "Version history": "Cronologia versioni",
    "Browse the full change log of every documented release.":
        "Sfoglia il changelog completo di ogni release documentata.",
    "Release notes file is missing from the build.":
        "Il file delle note di rilascio non è incluso nella build.",
    "(no version sections parsed)":
        "(nessuna sezione di versione trovata)",
    "GameBaiters Soundboard v%1":
        "GameBaiters Soundboard v%1",
    "No file assigned":
        "Nessun file assegnato",
    "Unsupported format or corrupt file":
        "Formato non supportato o file corrotto",
    "%1 — %2": "%1 — %2",
    "WAV (PCM 16-bit) (*.wav);;FLAC (lossless) (*.flac);;OGG Vorbis (*.ogg);;AAC / M4A (*.m4a);;All files (*.*)":
        "WAV (PCM 16-bit) (*.wav);;FLAC (lossless) (*.flac);;OGG Vorbis (*.ogg);;AAC / M4A (*.m4a);;Tutti i file (*.*)",
    # --- HowTo section titles ---
    "1. Getting started": "1. Per iniziare",
    "2. Sound buttons": "2. Pulsanti audio",
    "3. Cropping and waveform editing":
        "3. Crop e modifica della forma d&apos;onda",
    "4. Playing and transport": "4. Riproduzione e controlli",
    "5. Channels": "5. Canali",
    "6. Volume control": "6. Controllo del volume",
    "7. FX panel (pitch / speed / reverb)":
        "7. Pannello FX (pitch / velocità / riverbero)",
    "8. The audio sandbox": "8. Audio sandbox",
    "9. 3D / HRTF spatial audio":
        "9. Audio spaziale 3D / HRTF",
    "10. Paulstretch": "10. Paulstretch",
    "11. The DSP effects (the other 13)":
        "11. Gli effetti DSP (gli altri 13)",
    "12. Extras: ducking, random, normalize":
        "12. Extra: ducking, random, normalizzazione",
    "13. Presets, copy / paste":
        "13. Preset, copia / incolla",
    "14. Macros": "14. Macro",
    "15. Profiles": "15. Profili",
    "16. Hotkeys": "16. Scorciatoie",
    "17. Audio export": "17. Esportazione audio",
    "18. Theme": "18. Tema",
    "19. Language": "19. Lingua",
    "20. Settings overview":
        "20. Panoramica impostazioni",
    "21. Updates and About":
        "21. Aggiornamenti e Informazioni",
    # --- HowTo section bodies (HTML escaped) ---
    "&lt;p&gt;The soundboard is a TeamSpeak 3 plugin. Open it from &lt;b&gt;Plugins&lt;/b&gt; &amp;rarr; &lt;b&gt;Open GameBaiters Soundboard&lt;/b&gt;. The window is independent from TS3 and can be moved, resized or maximised.&lt;/p&gt;&lt;p&gt;You must be &lt;b&gt;connected to a server&lt;/b&gt; for sound to be sent into your voice channel. While disconnected the window dims and shows a notice, but you can still arrange buttons, edit effects and tune the layout.&lt;/p&gt;&lt;p&gt;The window has four areas:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Sound button grid&lt;/b&gt; at the top &amp;mdash; assign / fire sounds, drag to rearrange, filter via the search bar above.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Channels&lt;/b&gt; in the middle &amp;mdash; one playback lane each, stacked vertically.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Profile selector&lt;/b&gt; P1&amp;ndash;P4 &amp;mdash; switch between four independent layouts.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Control bar&lt;/b&gt; at the bottom &amp;mdash; add / remove channel, stop / pause all, settings.&lt;/li&gt;&lt;/ul&gt;":
        "&lt;p&gt;La soundboard è un plugin per TeamSpeak 3. Aprila da &lt;b&gt;Plugin&lt;/b&gt; &amp;rarr; &lt;b&gt;Apri GameBaiters Soundboard&lt;/b&gt;. La finestra è indipendente da TS3 e si può spostare, ridimensionare o massimizzare.&lt;/p&gt;&lt;p&gt;Devi essere &lt;b&gt;connesso a un server&lt;/b&gt; perché l&apos;audio venga inviato nel canale vocale. Quando sei disconnesso la finestra si oscura e mostra un avviso, ma puoi comunque sistemare i pulsanti, modificare gli effetti e regolare il layout.&lt;/p&gt;&lt;p&gt;La finestra ha quattro aree:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Griglia dei pulsanti&lt;/b&gt; in alto &amp;mdash; assegna / lancia suoni, trascina per riorganizzare, filtra con la barra di ricerca.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Canali&lt;/b&gt; al centro &amp;mdash; un canale per ogni linea di riproduzione, impilati verticalmente.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Selettore profilo&lt;/b&gt; P1&amp;ndash;P4 &amp;mdash; passa tra quattro layout indipendenti.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Barra di controllo&lt;/b&gt; in basso &amp;mdash; aggiungi / rimuovi canale, ferma / metti in pausa tutto, impostazioni.&lt;/li&gt;&lt;/ul&gt;",

    "&lt;p&gt;Every grid cell is a button. Three ways to assign a sound:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Drag &amp;amp; drop&lt;/b&gt; an audio file from Explorer / Finder onto a cell.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Right-click&lt;/b&gt; a cell &amp;rarr; &lt;b&gt;Edit&lt;/b&gt; to open the full button editor (file picker, label, colour, image, crop, hotkey, looping, per-button FX).&lt;/li&gt;&lt;li&gt;Drag an audio file directly onto a &lt;b&gt;channel&lt;/b&gt; instead of a button to play it immediately without saving a cell.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Supported formats:&lt;/b&gt; MP3, WAV, OGG, FLAC, AAC, M4A, MP4, MKV, AVI, WMA, FLV, OPUS &amp;mdash; anything FFmpeg can decode.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Three button types:&lt;/b&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Audio&lt;/b&gt; &amp;mdash; plays a sound file. Default for any drag &amp;amp; drop.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Macro&lt;/b&gt; &amp;mdash; restores a saved snapshot of every channel at once (see section 13).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Special&lt;/b&gt; &amp;mdash; bound actions such as stop-all.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Customising a button:&lt;/b&gt; in the editor you can set a custom label (overrides the filename), a custom background colour, a background image, looping, per-button volume, a TeamSpeak hotkey, and a crop range (see the next section). Drag buttons in the grid to rearrange them. The &lt;b&gt;search bar&lt;/b&gt; above the grid filters by label. Grid size (rows &amp;times; columns) is set in Settings &amp;rarr; &lt;b&gt;Layout&lt;/b&gt;.&lt;/p&gt;":
        "&lt;p&gt;Ogni cella della griglia è un pulsante. Tre modi per assegnare un suono:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Trascina &amp;amp; rilascia&lt;/b&gt; un file audio da Esplora risorse / Finder sopra una cella.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Clic destro&lt;/b&gt; su una cella &amp;rarr; &lt;b&gt;Modifica&lt;/b&gt; per aprire l&apos;editor completo del pulsante (file picker, etichetta, colore, immagine, crop, hotkey, loop, FX per pulsante).&lt;/li&gt;&lt;li&gt;Trascina un file audio direttamente su un &lt;b&gt;canale&lt;/b&gt; invece che su un pulsante per riprodurlo subito senza salvare una cella.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Formati supportati:&lt;/b&gt; MP3, WAV, OGG, FLAC, AAC, M4A, MP4, MKV, AVI, WMA, FLV, OPUS &amp;mdash; tutto quello che FFmpeg riesce a decodificare.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Tre tipi di pulsante:&lt;/b&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Audio&lt;/b&gt; &amp;mdash; riproduce un file. Default per qualsiasi drag &amp;amp; drop.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Macro&lt;/b&gt; &amp;mdash; ripristina lo snapshot salvato di ogni canale tutto insieme (vedi sezione 13).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Speciale&lt;/b&gt; &amp;mdash; azioni come stop-all.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Personalizzare un pulsante:&lt;/b&gt; nell&apos;editor puoi impostare etichetta personalizzata (sovrascrive il nome file), colore di sfondo, immagine di sfondo, loop, volume per pulsante, una hotkey di TeamSpeak e un intervallo di crop (vedi sezione successiva). Trascina i pulsanti nella griglia per riorganizzarli. La &lt;b&gt;barra di ricerca&lt;/b&gt; sopra la griglia filtra per etichetta. La dimensione della griglia (righe &amp;times; colonne) si imposta in Impostazioni &amp;rarr; &lt;b&gt;Layout&lt;/b&gt;.&lt;/p&gt;",

    "&lt;p&gt;Every sound can be &lt;b&gt;cropped&lt;/b&gt; to play only a slice of the file. Two ways to do it:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Button editor:&lt;/b&gt; set start / end in seconds (or %) in the &lt;b&gt;Crop&lt;/b&gt; group.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Waveform right-click:&lt;/b&gt; while a channel is showing a sound, right-click the waveform &amp;rarr; &lt;b&gt;Set start here&lt;/b&gt; / &lt;b&gt;Set end here&lt;/b&gt;. The change is applied live to the running playback AND saved back to the originating button.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Coloured &lt;b&gt;start / end marker lines&lt;/b&gt; with a dim overlay show the crop range right on the waveform. The cursor is clamped inside the markers &amp;mdash; skip / seek can not escape the crop.&lt;/p&gt;&lt;p&gt;The crop marker overlay can be hidden via Settings &amp;rarr; &lt;b&gt;Channels&lt;/b&gt; &amp;rarr; &lt;b&gt;Show crop markers&lt;/b&gt;.&lt;/p&gt;":
        "&lt;p&gt;Ogni suono può essere &lt;b&gt;croppato&lt;/b&gt; per riprodurre solo una porzione del file. Due modi:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Editor del pulsante:&lt;/b&gt; imposta inizio / fine in secondi (o %) nel gruppo &lt;b&gt;Crop&lt;/b&gt;.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Clic destro sulla forma d&apos;onda:&lt;/b&gt; mentre un canale mostra un suono, clic destro sulla waveform &amp;rarr; &lt;b&gt;Imposta inizio qui&lt;/b&gt; / &lt;b&gt;Imposta fine qui&lt;/b&gt;. La modifica si applica subito alla riproduzione corrente E viene salvata nel pulsante che ha originato il suono.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Marker colorati di inizio / fine&lt;/b&gt; con un overlay scuro mostrano l&apos;intervallo di crop direttamente sulla forma d&apos;onda. Il cursore resta bloccato dentro i marker &amp;mdash; skip / seek non possono uscire dal crop.&lt;/p&gt;&lt;p&gt;L&apos;overlay dei marker si può nascondere da Impostazioni &amp;rarr; &lt;b&gt;Canali&lt;/b&gt; &amp;rarr; &lt;b&gt;Mostra marker di crop&lt;/b&gt;.&lt;/p&gt;",

    "&lt;p&gt;Click a button to play its sound on the next free channel. The &lt;b&gt;waveform view&lt;/b&gt; shows playback progress &amp;mdash; click anywhere on it to seek.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Transport controls&lt;/b&gt; (per channel):&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Play / Pause / Stop&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;Skip&lt;/b&gt; &amp;plusmn;5 s and &amp;plusmn;10 s&lt;/li&gt;&lt;li&gt;&lt;b&gt;Loop&lt;/b&gt; &amp;mdash; restarts the sound at the crop start when it reaches the end&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reverse&lt;/b&gt; &amp;mdash; plays the sound backwards in real time. Toggle it mid-playback and the direction flips instantly; pitch / speed / reverb / loop / crop markers all behave exactly as in forward play. From v2.2.9 the reverse start is decoded in 0.5 s chunks around the current cursor, so the flip is instant even on multi-minute files &amp;mdash; no more freeze.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Global controls&lt;/b&gt; in the bottom bar:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Stop all&lt;/b&gt; / &lt;b&gt;Pause all&lt;/b&gt; &amp;mdash; act on every channel.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset channels&lt;/b&gt; (in Settings) &amp;mdash; clears volume / FX / files on every channel after a confirmation prompt.&lt;/li&gt;&lt;/ul&gt;":
        "&lt;p&gt;Clicca un pulsante per riprodurre il suono sul prossimo canale libero. La &lt;b&gt;vista forma d&apos;onda&lt;/b&gt; mostra il progresso della riproduzione &amp;mdash; clicca un punto qualsiasi per fare seek.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Controlli di trasporto&lt;/b&gt; (per canale):&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Play / Pausa / Stop&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;Skip&lt;/b&gt; &amp;plusmn;5 s e &amp;plusmn;10 s&lt;/li&gt;&lt;li&gt;&lt;b&gt;Loop&lt;/b&gt; &amp;mdash; riavvia il suono dall&apos;inizio del crop quando arriva alla fine&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reverse&lt;/b&gt; &amp;mdash; riproduce il suono al contrario in tempo reale. Attivalo durante la riproduzione e la direzione si inverte istantaneamente; pitch / velocità / riverbero / loop / marker di crop si comportano esattamente come in forward. Dalla v2.2.9 l&apos;inizio del reverse viene decodificato in chunk da 0,5 s attorno al cursore corrente, quindi il cambio è immediato anche su file di diversi minuti &amp;mdash; niente più freeze.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Controlli globali&lt;/b&gt; nella barra in basso:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Ferma tutto&lt;/b&gt; / &lt;b&gt;Pausa tutto&lt;/b&gt; &amp;mdash; agiscono su ogni canale.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset canali&lt;/b&gt; (in Impostazioni) &amp;mdash; azzera volume / FX / file su ogni canale dopo una conferma.&lt;/li&gt;&lt;/ul&gt;",

    "&lt;p&gt;A &lt;b&gt;channel&lt;/b&gt; is one independent playback lane: it has its own file, volume, FX, waveform, transport, peak meter and audio sandbox. Add channels with &lt;b&gt;+ Add channel&lt;/b&gt;; the first channel is always present.&lt;/p&gt;&lt;p&gt;Channel titles are editable &amp;mdash; click the title to rename. The &lt;b&gt;peak meter&lt;/b&gt; shows level (cyan = normal, red = clipping) and the LED columns above each EQ band visualise the live per-band energy when the EQ is open.&lt;/p&gt;&lt;p&gt;Each channel&apos;s state (volume, FX, sandbox, current sound, position, loop / reverse toggles) is saved and restored across restarts when &lt;b&gt;Restore last session on startup&lt;/b&gt; is enabled in Settings.&lt;/p&gt;&lt;p&gt;The &lt;b&gt;Reverse&lt;/b&gt; button on a channel is sticky: every new sound you fire on that channel inherits the reverse direction. Toggle it off to go back to forward play.&lt;/p&gt;":
        "&lt;p&gt;Un &lt;b&gt;canale&lt;/b&gt; è una linea di riproduzione indipendente: ha il suo file, volume, FX, forma d&apos;onda, controlli di trasporto, peak meter e audio sandbox. Aggiungi canali con &lt;b&gt;+ Aggiungi canale&lt;/b&gt;; il primo canale è sempre presente.&lt;/p&gt;&lt;p&gt;I titoli dei canali sono modificabili &amp;mdash; clicca il titolo per rinominare. Il &lt;b&gt;peak meter&lt;/b&gt; mostra il livello (ciano = normale, rosso = clipping) e le colonne LED sopra ogni banda EQ visualizzano l&apos;energia per banda in tempo reale quando l&apos;EQ è aperto.&lt;/p&gt;&lt;p&gt;Lo stato di ogni canale (volume, FX, sandbox, suono corrente, posizione, toggle loop / reverse) viene salvato e ripristinato tra un avvio e l&apos;altro se &lt;b&gt;Ripristina ultima sessione all&apos;avvio&lt;/b&gt; è attivo in Impostazioni.&lt;/p&gt;&lt;p&gt;Il pulsante &lt;b&gt;Reverse&lt;/b&gt; di un canale è persistente: ogni nuovo suono che lanci su quel canale eredita la direzione reverse. Disattivalo per tornare alla riproduzione normale.&lt;/p&gt;",

    "&lt;p&gt;Every channel has &lt;b&gt;two&lt;/b&gt; volume sliders:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Local&lt;/b&gt; &amp;mdash; how loud &lt;i&gt;you&lt;/i&gt; hear the sound.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Remote&lt;/b&gt; &amp;mdash; how loud &lt;i&gt;others&lt;/i&gt; on the server hear it. This is the value the TS3 client mixes into the voice stream.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;The &lt;b&gt;Link&lt;/b&gt; toggle moves both sliders together. A &lt;b&gt;Global volume&lt;/b&gt; master at the top scales everything before per-channel Local / Remote. Each button also has its own per-button volume in its editor &amp;mdash; it stacks on top of the channel volume.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Earrape protection&lt;/b&gt; in Settings clips your LOCAL output at a safe ceiling, so an accidental loud clip can never deafen you. It never touches the Remote stream.&lt;/p&gt;":
        "&lt;p&gt;Ogni canale ha &lt;b&gt;due&lt;/b&gt; slider del volume:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Locale&lt;/b&gt; &amp;mdash; quanto forte senti il suono &lt;i&gt;tu&lt;/i&gt;.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Remoto&lt;/b&gt; &amp;mdash; quanto forte lo sentono &lt;i&gt;gli altri&lt;/i&gt; sul server. È il valore che il client TS3 mixa nel flusso vocale.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Il toggle &lt;b&gt;Link&lt;/b&gt; muove entrambi gli slider insieme. Un &lt;b&gt;Volume globale&lt;/b&gt; master in alto scala tutto prima dei Locale / Remoto per canale. Ogni pulsante ha anche un volume per pulsante nel suo editor &amp;mdash; si somma sopra al volume del canale.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Protezione earrape&lt;/b&gt; in Impostazioni clippa l&apos;uscita LOCALE a un tetto sicuro, così un clip improvvisamente forte non può mai assordarti. Non tocca mai il flusso Remoto.&lt;/p&gt;",

    "&lt;p&gt;The compact &lt;b&gt;FX panel&lt;/b&gt; on each channel offers three quick, real-time effects:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Pitch&lt;/b&gt; &amp;mdash; shift pitch independently of speed (0.33&amp;times;&amp;ndash;3.0&amp;times;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Speed&lt;/b&gt; &amp;mdash; change playback rate independently of pitch.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reverb&lt;/b&gt; &amp;mdash; quick room ambience (0&amp;ndash;100).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;The &lt;b&gt;Sync&lt;/b&gt; toggle locks pitch and speed together for a chipmunk / slow-motion effect.&lt;/p&gt;&lt;p&gt;With &lt;b&gt;Remember pitch / speed / reverb per channel&lt;/b&gt; enabled in Settings, these values persist across restarts. With &lt;b&gt;Enable custom FX&lt;/b&gt; off in Settings the panel is hidden &amp;mdash; useful if you only want clean playback.&lt;/p&gt;&lt;p&gt;The FX panel is the &lt;i&gt;quick&lt;/i&gt; effects strip. For the deep 14-effect chain, open the per-channel &lt;b&gt;Audio sandbox&lt;/b&gt; (next section).&lt;/p&gt;":
        "&lt;p&gt;Il &lt;b&gt;pannello FX&lt;/b&gt; compatto su ogni canale offre tre effetti rapidi in tempo reale:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Pitch&lt;/b&gt; &amp;mdash; sposta il pitch indipendentemente dalla velocità (0,33&amp;times;&amp;ndash;3,0&amp;times;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Velocità&lt;/b&gt; &amp;mdash; cambia la velocità di riproduzione indipendentemente dal pitch.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Riverbero&lt;/b&gt; &amp;mdash; ambienza rapida (0&amp;ndash;100).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Il toggle &lt;b&gt;Sync&lt;/b&gt; blocca pitch e velocità insieme per un effetto chipmunk / slow-motion.&lt;/p&gt;&lt;p&gt;Con &lt;b&gt;Ricorda pitch / velocità / riverbero per canale&lt;/b&gt; attivo in Impostazioni, questi valori persistono tra un avvio e l&apos;altro. Con &lt;b&gt;Abilita FX personalizzati&lt;/b&gt; disattivo in Impostazioni il pannello è nascosto &amp;mdash; utile se vuoi solo riproduzione pulita.&lt;/p&gt;&lt;p&gt;Il pannello FX è la striscia di effetti &lt;i&gt;rapidi&lt;/i&gt;. Per la catena profonda da 14 effetti, apri l&apos;&lt;b&gt;Audio sandbox&lt;/b&gt; per canale (sezione successiva).&lt;/p&gt;",

    "&lt;p&gt;The &lt;b&gt;audio sandbox&lt;/b&gt; is a per-channel rack of &lt;b&gt;14 DSP effects&lt;/b&gt; arranged in a re-orderable pipeline. Open it from the channel&apos;s sandbox button.&lt;/p&gt;&lt;p&gt;A single &lt;b&gt;master switch&lt;/b&gt; at the top enables or bypasses the whole chain at zero CPU cost when off &amp;mdash; every value is kept so you can A/B instantly.&lt;/p&gt;&lt;p&gt;The &lt;b&gt;Pipeline order&lt;/b&gt; bar near the top shows the chain as coloured blocks in processing order:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Drag&lt;/b&gt; a block to move it earlier / later in the chain.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Click&lt;/b&gt; a block (without dragging) to scroll to that effect&apos;s panel and open its accordion.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Paulstretch&lt;/b&gt; is pinned first and is not draggable &amp;mdash; it runs on a separate streaming feed before the rest of the chain.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset order&lt;/b&gt; restores the default chain (effect values are kept).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;The panel list below mirrors the pipeline order. Use the &lt;b&gt;search box&lt;/b&gt; to filter by name. Each module has its own enable toggle and a small reset button (per-module defaults).&lt;/p&gt;&lt;p&gt;The &lt;b&gt;Fold output to mono&lt;/b&gt; checkbox collapses the stereo image and is always applied LAST &amp;mdash; it is not a reorderable module.&lt;/p&gt;&lt;p&gt;The whole sandbox state is saved per channel and travels inside sandbox presets, pipeline order included.&lt;/p&gt;":
        "&lt;p&gt;L&apos;&lt;b&gt;audio sandbox&lt;/b&gt; è un rack per canale di &lt;b&gt;14 effetti DSP&lt;/b&gt; in una pipeline riorganizzabile. Aprila dal pulsante sandbox del canale.&lt;/p&gt;&lt;p&gt;Un &lt;b&gt;master switch&lt;/b&gt; in alto attiva o bypassa tutta la catena a costo CPU zero quando è spento &amp;mdash; ogni valore viene mantenuto, così puoi fare A/B subito.&lt;/p&gt;&lt;p&gt;La barra &lt;b&gt;Ordine pipeline&lt;/b&gt; vicino all&apos;alto mostra la catena come blocchi colorati in ordine di elaborazione:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Trascina&lt;/b&gt; un blocco per spostarlo prima / dopo nella catena.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Clicca&lt;/b&gt; un blocco (senza trascinare) per scorrere al pannello di quell&apos;effetto e aprire la sua fisarmonica.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Paulstretch&lt;/b&gt; è fissato come primo e non è trascinabile &amp;mdash; gira su un feed streaming separato prima del resto della catena.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset ordine&lt;/b&gt; ripristina la catena di default (i valori degli effetti restano).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;La lista pannelli sotto rispecchia l&apos;ordine della pipeline. Usa la &lt;b&gt;casella di ricerca&lt;/b&gt; per filtrare per nome. Ogni modulo ha il suo toggle di attivazione e un pulsante di reset (default per modulo).&lt;/p&gt;&lt;p&gt;La checkbox &lt;b&gt;Riduci uscita a mono&lt;/b&gt; collassa l&apos;immagine stereo ed è sempre applicata PER ULTIMA &amp;mdash; non è un modulo riorganizzabile.&lt;/p&gt;&lt;p&gt;Tutto lo stato della sandbox viene salvato per canale e viaggia dentro i preset sandbox, ordine della pipeline incluso.&lt;/p&gt;",

    "&lt;p&gt;The &lt;b&gt;Spatial&lt;/b&gt; stage places the sound in 3D space. Modes:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Off&lt;/b&gt; &amp;mdash; no spatial processing.&lt;/li&gt;&lt;li&gt;&lt;b&gt;L/R Pan&lt;/b&gt; &amp;mdash; simple equal-power stereo balance.&lt;/li&gt;&lt;li&gt;&lt;b&gt;3D Manual&lt;/b&gt; &amp;mdash; drag a virtual source on the positional pad; set elevation, distance and stereo width.&lt;/li&gt;&lt;li&gt;&lt;b&gt;3D Rotate&lt;/b&gt; &amp;mdash; the source orbits your head at a chosen RPM and radius.&lt;/li&gt;&lt;li&gt;&lt;b&gt;8D preset&lt;/b&gt; &amp;mdash; the classic &apos;YouTube 8D&apos; recipe: orbit + head sway + tight width.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Spatial mix&lt;/b&gt; crossfades between processed and raw stereo &amp;mdash; pull it back if the result feels too narrow. &lt;b&gt;Ambience&lt;/b&gt; adds room reflections that push the sound out of your head.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Engine choice (Classic vs Leia):&lt;/b&gt; the 3D modes can be rendered by two engines, selected per channel:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Classic&lt;/b&gt; &amp;mdash; the original Brown-Duda parametric model. Lightweight, zero dependencies, the original soundboard sound.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Leia&lt;/b&gt; &amp;mdash; measured-HRTF convolution using a MIT KEMAR SOFA dataset, plus a shoebox-room early-reflection engine. Much more convincing externalisation, especially through headphones.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Leia exposes its own controls: &lt;b&gt;Reflections&lt;/b&gt; on/off + level, &lt;b&gt;Room size&lt;/b&gt;, &lt;b&gt;Room type&lt;/b&gt; (13 presets ranging from Studio to Cathedral to Underwater &amp;mdash; each preset has a unique Schroeder diffuse-tail signature), &lt;b&gt;Clarity&lt;/b&gt; (early/late balance) and &lt;b&gt;Width&lt;/b&gt;. Switching from Classic to Leia is instant &amp;mdash; the audio thread keeps running while the SOFA loads in the background.&lt;/p&gt;":
        "&lt;p&gt;Lo stadio &lt;b&gt;Spaziale&lt;/b&gt; colloca il suono nello spazio 3D. Modalità:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Off&lt;/b&gt; &amp;mdash; nessuna elaborazione spaziale.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Pan L/R&lt;/b&gt; &amp;mdash; bilanciamento stereo equal-power.&lt;/li&gt;&lt;li&gt;&lt;b&gt;3D Manuale&lt;/b&gt; &amp;mdash; trascina una sorgente virtuale sul pad posizionale; imposta elevazione, distanza e larghezza stereo.&lt;/li&gt;&lt;li&gt;&lt;b&gt;3D Rotate&lt;/b&gt; &amp;mdash; la sorgente orbita attorno alla tua testa a RPM e raggio scelti.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Preset 8D&lt;/b&gt; &amp;mdash; il classico &apos;YouTube 8D&apos;: orbita + head sway + larghezza stretta.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Mix spaziale&lt;/b&gt; fa il crossfade tra stereo elaborato e raw &amp;mdash; abbassalo se il risultato sembra troppo stretto. &lt;b&gt;Ambienza&lt;/b&gt; aggiunge riflessioni di stanza che spingono il suono fuori dalla testa.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Scelta engine (Classic vs Leia):&lt;/b&gt; le modalità 3D si possono renderizzare con due engine, scelti per canale:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Classic&lt;/b&gt; &amp;mdash; il modello parametrico Brown-Duda originale. Leggero, zero dipendenze, il suono soundboard originale.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Leia&lt;/b&gt; &amp;mdash; convoluzione HRTF misurata su dataset SOFA MIT KEMAR, più un motore di riflessioni precoci shoebox-room. Esternalizzazione molto più convincente, soprattutto in cuffia.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Leia espone i suoi controlli: &lt;b&gt;Riflessioni&lt;/b&gt; on/off + livello, &lt;b&gt;Dimensione stanza&lt;/b&gt;, &lt;b&gt;Tipo stanza&lt;/b&gt; (13 preset da Studio a Cattedrale ad Underwater &amp;mdash; ogni preset ha una firma di coda diffusa di Schroeder unica), &lt;b&gt;Clarity&lt;/b&gt; (bilanciamento early/late) e &lt;b&gt;Larghezza&lt;/b&gt;. Passare da Classic a Leia è istantaneo &amp;mdash; il thread audio continua a girare mentre il SOFA si carica in background.&lt;/p&gt;",

    "&lt;p&gt;&lt;b&gt;Paulstretch&lt;/b&gt; is an extreme time-stretch (1&amp;times;&amp;ndash;50&amp;times;) that keeps pitch while slowing the sound into a wide, diffuse drone. It is the first module in the sandbox list and its pipeline position is fixed.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Factor&lt;/b&gt; sets how much slower it plays; &lt;b&gt;Window&lt;/b&gt; sets the FFT analysis size (bigger = smoother and more &apos;frozen&apos;, smaller = grittier and more rhythmic).&lt;/p&gt;&lt;p&gt;Paulstretch runs on a separate streaming feed before the rest of the chain. While it is on the server receives a clean, stretched stream &amp;mdash; the same audio you hear locally.&lt;/p&gt;":
        "&lt;p&gt;&lt;b&gt;Paulstretch&lt;/b&gt; è un time-stretch estremo (1&amp;times;&amp;ndash;50&amp;times;) che mantiene il pitch rallentando il suono in un drone ampio e diffuso. È il primo modulo nella lista sandbox e la sua posizione nella pipeline è fissa.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Fattore&lt;/b&gt; imposta quanto rallenta; &lt;b&gt;Finestra&lt;/b&gt; imposta la dimensione di analisi FFT (più grande = più liscio e &apos;congelato&apos;, più piccolo = più sporco e ritmico).&lt;/p&gt;&lt;p&gt;Paulstretch gira su un feed streaming separato prima del resto della catena. Quando è attivo il server riceve uno stream pulito e stretchato &amp;mdash; lo stesso audio che senti localmente.&lt;/p&gt;",

    "&lt;p&gt;Listed in the default pipeline order:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;16-band EQ&lt;/b&gt; &amp;mdash; ISO 2/3-octave graphic equaliser, &amp;plusmn;12 dB per band, with live per-band LED level meters and Save / Load EQ presets. Right-click a band &amp;rarr; reset / +12 / -12 dB. Mouse wheel adjusts by 1 dB (Shift = 3 dB).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Compressor&lt;/b&gt; &amp;mdash; evens out dynamics (threshold, ratio, attack, release, knee, makeup gain).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Saturator&lt;/b&gt; &amp;mdash; adds warmth / grit; soft, tube, tape or hard-clip modes.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Spatial&lt;/b&gt; &amp;mdash; see section 9.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Chorus&lt;/b&gt; &amp;mdash; thickens the sound with detuned voices.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Flanger&lt;/b&gt; &amp;mdash; classic sweeping jet effect.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Flangus&lt;/b&gt; &amp;mdash; flanger / chorus hybrid with multi-voice spread.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Phaser&lt;/b&gt; &amp;mdash; sweeping notch filter, up to 12 stages.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Delay&lt;/b&gt; &amp;mdash; echo up to 3 s with damping and optional ping-pong.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reverb&lt;/b&gt; &amp;mdash; algorithmic room ambience (in addition to Leia&apos;s measured reflections).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Limiter&lt;/b&gt; &amp;mdash; brick-wall limiter, compressor or noise gate.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Bitcrusher&lt;/b&gt; &amp;mdash; reduces bit depth and sample rate for a lo-fi sound.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Generation Loss&lt;/b&gt; &amp;mdash; simulates repeated re-encoding (the &apos;deep-fried&apos; effect).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Each effect has its own enable toggle, per-module reset button and is fully drag-reorderable in the pipeline. Live state persists across restarts.&lt;/p&gt;":
        "&lt;p&gt;Elencati nell&apos;ordine pipeline di default:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;EQ a 16 bande&lt;/b&gt; &amp;mdash; equalizzatore grafico ISO 2/3 di ottava, &amp;plusmn;12 dB per banda, con misuratori LED di livello per banda in tempo reale e Save / Load preset EQ. Clic destro su una banda &amp;rarr; reset / +12 / -12 dB. La rotella regola di 1 dB (Shift = 3 dB).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Compressore&lt;/b&gt; &amp;mdash; livella le dinamiche (threshold, ratio, attack, release, knee, makeup gain).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Saturatore&lt;/b&gt; &amp;mdash; aggiunge calore / grit; modalità soft, tube, tape o hard-clip.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Spaziale&lt;/b&gt; &amp;mdash; vedi sezione 9.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Chorus&lt;/b&gt; &amp;mdash; ispessisce il suono con voci stonate.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Flanger&lt;/b&gt; &amp;mdash; classico effetto jet che si muove.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Flangus&lt;/b&gt; &amp;mdash; ibrido flanger / chorus con multi-voce.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Phaser&lt;/b&gt; &amp;mdash; filtro notch in movimento, fino a 12 stadi.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Delay&lt;/b&gt; &amp;mdash; echo fino a 3 s con damping e ping-pong opzionale.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Riverbero&lt;/b&gt; &amp;mdash; ambienza di stanza algoritmica (oltre alle riflessioni misurate di Leia).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Limiter&lt;/b&gt; &amp;mdash; brick-wall limiter, compressore o noise gate.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Bitcrusher&lt;/b&gt; &amp;mdash; riduce profondità di bit e sample rate per un suono lo-fi.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Generation Loss&lt;/b&gt; &amp;mdash; simula ricodifiche ripetute (l&apos;effetto &apos;deep-fried&apos;).&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Ogni effetto ha il suo toggle di attivazione, un pulsante di reset per modulo ed è completamente drag-riorganizzabile nella pipeline. Lo stato live persiste tra un avvio e l&apos;altro.&lt;/p&gt;",

    "&lt;p&gt;The sandbox also includes a few global features that are not ordered as pipeline modules:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Auto normalize (LUFS)&lt;/b&gt; &amp;mdash; EBU R128 single-pass loudness normalisation targeting -16 LUFS integrated / -1 dBTP. Levels every clip without you having to ride the volume.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Random pitch jitter&lt;/b&gt; &amp;mdash; on every play (and every loop iteration) the pitch is shifted by a random number of cents within the range you set. Great for spam buttons that should never sound identical twice.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Sidechain ducking&lt;/b&gt; &amp;mdash; while this channel is transmitting, it attenuates every OTHER channel by N dB. Smooth attack / release so the duck doesn&apos;t pump.&lt;/li&gt;&lt;/ul&gt;":
        "&lt;p&gt;La sandbox include anche alcune funzioni globali che non sono ordinate come moduli pipeline:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Auto normalize (LUFS)&lt;/b&gt; &amp;mdash; normalizzazione di loudness EBU R128 single-pass che punta a -16 LUFS integrato / -1 dBTP. Livella ogni clip senza che tu debba regolare il volume a mano.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Random pitch jitter&lt;/b&gt; &amp;mdash; a ogni play (e a ogni iterazione di loop) il pitch viene spostato di un numero random di cents nel range che imposti. Ottimo per pulsanti spam che non devono mai suonare identici due volte.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Sidechain ducking&lt;/b&gt; &amp;mdash; mentre questo canale trasmette, attenua ogni altro canale di N dB. Attack / release smussati così il duck non pompa.&lt;/li&gt;&lt;/ul&gt;",

    "&lt;p&gt;You can save and reload named presets:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;EQ presets&lt;/b&gt; &amp;mdash; just the 16 EQ bands.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Sandbox presets&lt;/b&gt; &amp;mdash; every effect, every parameter and the pipeline order.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Presets are stored in a per-user INI so they survive reinstalls and travel between profiles.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Copy / Paste&lt;/b&gt; buttons in the sandbox dialog move a complete setup between channels through the clipboard as a short text string &amp;mdash; perfect for matching all channels to one chain.&lt;/p&gt;":
        "&lt;p&gt;Puoi salvare e ricaricare preset nominati:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Preset EQ&lt;/b&gt; &amp;mdash; solo le 16 bande EQ.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Preset sandbox&lt;/b&gt; &amp;mdash; ogni effetto, ogni parametro e l&apos;ordine della pipeline.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;I preset sono salvati in un INI per utente, sopravvivono alle reinstallazioni e viaggiano tra i profili.&lt;/p&gt;&lt;p&gt;I pulsanti &lt;b&gt;Copia / Incolla&lt;/b&gt; nel dialogo sandbox spostano un setup completo tra canali via clipboard come stringa di testo &amp;mdash; perfetto per allineare tutti i canali su una catena.&lt;/p&gt;",

    "&lt;p&gt;A &lt;b&gt;macro button&lt;/b&gt; freezes the state of &lt;i&gt;every&lt;/i&gt; channel (volumes, FX, files, full sandbox state) into one button. Pressing it later restores that whole snapshot in one click.&lt;/p&gt;&lt;p&gt;Create a macro by right-clicking a free cell &amp;rarr; &lt;b&gt;Make macro&lt;/b&gt;. Macro buttons carry a visual marker so they&apos;re easy to spot.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Undo macro&lt;/b&gt; (previously &apos;Restore pre-macro&apos;) reverts to the exact state the channels were in just before the macro fired &amp;mdash; use it when you want to A/B between your live setup and a saved snapshot.&lt;/p&gt;":
        "&lt;p&gt;Un &lt;b&gt;pulsante macro&lt;/b&gt; congela lo stato di &lt;i&gt;ogni&lt;/i&gt; canale (volumi, FX, file, stato completo della sandbox) in un solo pulsante. Premendolo dopo ripristina tutto lo snapshot con un clic.&lt;/p&gt;&lt;p&gt;Crea una macro con clic destro su una cella vuota &amp;rarr; &lt;b&gt;Crea macro&lt;/b&gt;. I pulsanti macro hanno un marcatore visivo per riconoscerli subito.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Annulla macro&lt;/b&gt; (prima &apos;Restore pre-macro&apos;) ripristina lo stato esatto dei canali appena prima che la macro partisse &amp;mdash; usalo quando vuoi fare A/B tra il setup live e uno snapshot salvato.&lt;/p&gt;",

    "&lt;p&gt;The soundboard has &lt;b&gt;4 independent profiles&lt;/b&gt; (P1&amp;ndash;P4), each with its own button grid, grid size, macros and per-profile settings. Switch with the P1&amp;ndash;P4 buttons in the top bar or via a TS3 hotkey.&lt;/p&gt;&lt;p&gt;Profiles can be &lt;b&gt;exported as JSON&lt;/b&gt; to back up or share. The exported file is human-readable and contains every button, every label, every colour and every macro. Importing a JSON profile is lossless.&lt;/p&gt;&lt;p&gt;The currently selected profile is automatically persisted &amp;mdash; the next start opens the same profile.&lt;/p&gt;":
        "&lt;p&gt;La soundboard ha &lt;b&gt;4 profili indipendenti&lt;/b&gt; (P1&amp;ndash;P4), ognuno con la sua griglia di pulsanti, dimensione griglia, macro e impostazioni per profilo. Cambia con i pulsanti P1&amp;ndash;P4 nella barra in alto o con una hotkey TS3.&lt;/p&gt;&lt;p&gt;I profili si possono &lt;b&gt;esportare come JSON&lt;/b&gt; per backup o condivisione. Il file esportato è leggibile e contiene ogni pulsante, etichetta, colore e macro. L&apos;importazione di un profilo JSON è lossless.&lt;/p&gt;&lt;p&gt;Il profilo selezionato viene salvato automaticamente &amp;mdash; il prossimo avvio apre lo stesso profilo.&lt;/p&gt;",

    "&lt;p&gt;Any button can be bound to a &lt;b&gt;TS3 hotkey&lt;/b&gt;. Open the button editor &amp;rarr; &lt;b&gt;Set hotkey...&lt;/b&gt; and follow the TS3 prompt to assign a key combo.&lt;/p&gt;&lt;p&gt;Enable &lt;b&gt;Show hotkeys on buttons&lt;/b&gt; in Settings to display the binding as a small label on each button &amp;mdash; very handy when you have dozens of bindings.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Disable hotkeys&lt;/b&gt; in Settings temporarily ignores all soundboard hotkeys without losing the bindings &amp;mdash; useful when you need to type something or play a game without firing sounds by accident.&lt;/p&gt;":
        "&lt;p&gt;Qualsiasi pulsante si può legare a una &lt;b&gt;hotkey TS3&lt;/b&gt;. Apri l&apos;editor del pulsante &amp;rarr; &lt;b&gt;Imposta hotkey...&lt;/b&gt; e segui il prompt di TS3 per assegnare una combinazione di tasti.&lt;/p&gt;&lt;p&gt;Attiva &lt;b&gt;Mostra hotkey sui pulsanti&lt;/b&gt; in Impostazioni per visualizzare il binding come piccola etichetta su ogni pulsante &amp;mdash; molto comodo quando hai decine di binding.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Disabilita hotkey&lt;/b&gt; in Impostazioni ignora temporaneamente tutte le hotkey della soundboard senza perdere i binding &amp;mdash; utile quando devi scrivere qualcosa o giocare senza far partire suoni per sbaglio.&lt;/p&gt;",

    "&lt;p&gt;&lt;b&gt;Audio export&lt;/b&gt; renders a sound to a 48 kHz stereo file with the &lt;i&gt;entire&lt;/i&gt; signal chain baked in: pitch, speed, reverb, the full sandbox DSP chain (including Paulstretch).&lt;/p&gt;&lt;p&gt;Supported output formats: &lt;b&gt;WAV&lt;/b&gt; (PCM 16-bit), &lt;b&gt;FLAC&lt;/b&gt; (lossless), &lt;b&gt;OGG Vorbis&lt;/b&gt; and &lt;b&gt;AAC-M4A&lt;/b&gt;. The format is picked automatically from the filename extension you choose in the save dialog.&lt;/p&gt;&lt;p&gt;Export runs in a background thread with a custom-painted progress bar; closing the dialog cancels the job cleanly. The exported file is bit-identical to what you would hear on playback.&lt;/p&gt;":
        "&lt;p&gt;L&apos;&lt;b&gt;export audio&lt;/b&gt; renderizza un suono in un file stereo 48 kHz con &lt;i&gt;tutta&lt;/i&gt; la catena di segnale applicata: pitch, velocità, riverbero, l&apos;intera catena DSP della sandbox (Paulstretch incluso).&lt;/p&gt;&lt;p&gt;Formati di output supportati: &lt;b&gt;WAV&lt;/b&gt; (PCM 16-bit), &lt;b&gt;FLAC&lt;/b&gt; (lossless), &lt;b&gt;OGG Vorbis&lt;/b&gt; e &lt;b&gt;AAC-M4A&lt;/b&gt;. Il formato si sceglie automaticamente dall&apos;estensione del nome file nel dialogo di salvataggio.&lt;/p&gt;&lt;p&gt;L&apos;export gira in un thread di background con barra di progresso disegnata custom; chiudere il dialogo annulla il lavoro in modo pulito. Il file esportato è bit-identico a quello che senti in playback.&lt;/p&gt;",

    "&lt;p&gt;In Settings &amp;rarr; &lt;b&gt;Theme&lt;/b&gt; you can recolour the soundboard with three colours (accent, waveform, background) plus a contrast slider. Over a dozen surface colours (button hover, dim text, panel border, etc.) are derived automatically from those three and applied live.&lt;/p&gt;&lt;p&gt;The theme is scoped to the soundboard &amp;mdash; it never leaks into the TeamSpeak client window.&lt;/p&gt;":
        "&lt;p&gt;In Impostazioni &amp;rarr; &lt;b&gt;Tema&lt;/b&gt; puoi ricolorare la soundboard con tre colori (accent, forma d&apos;onda, sfondo) più uno slider di contrasto. Più di una dozzina di colori di superficie (hover pulsanti, testo dim, bordo pannello, ecc.) vengono derivati automaticamente da questi tre e applicati subito.&lt;/p&gt;&lt;p&gt;Il tema è limitato alla soundboard &amp;mdash; non sborda mai nella finestra del client TeamSpeak.&lt;/p&gt;",

    "&lt;p&gt;The interface auto-selects &lt;b&gt;Italian&lt;/b&gt; when the system locale is Italian, English otherwise. You can override the language in Settings &amp;rarr; &lt;b&gt;Language&lt;/b&gt; at any time. The change applies on the next plugin start (a quick TS3 reload is enough).&lt;/p&gt;":
        "&lt;p&gt;L&apos;interfaccia seleziona automaticamente l&apos;&lt;b&gt;italiano&lt;/b&gt; quando il locale di sistema è italiano, inglese altrimenti. Puoi forzare la lingua da Impostazioni &amp;rarr; &lt;b&gt;Lingua&lt;/b&gt; in qualsiasi momento. Il cambio si applica al prossimo avvio del plugin (basta un reload veloce di TS3).&lt;/p&gt;",

    "&lt;p&gt;The Settings window collects every global option:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Layout&lt;/b&gt; &amp;mdash; grid rows / columns, hide waveform (compact view), audio meter visibility, hotkey display, crop markers, channel headers.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Channels&lt;/b&gt; &amp;mdash; remember FX per channel, restore last session, link new channels&apos; settings to the first channel.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Audio&lt;/b&gt; &amp;mdash; earrape protection, custom FX, audio sandbox, show export button.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Logs&lt;/b&gt; &amp;mdash; write debug log file (see &lt;b&gt;Plugins menu &amp;rarr; Show plugin log&lt;/b&gt;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset&lt;/b&gt; &amp;mdash; one-shot reset of channels, volumes, FX, files or sandbox settings (with a confirmation prompt).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Theme&lt;/b&gt; &amp;mdash; three colours + contrast.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Language&lt;/b&gt; &amp;mdash; auto / en / it.&lt;/li&gt;&lt;/ul&gt;":
        "&lt;p&gt;La finestra Impostazioni raccoglie ogni opzione globale:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;b&gt;Layout&lt;/b&gt; &amp;mdash; righe / colonne griglia, nascondi forma d&apos;onda (vista compatta), visibilità audio meter, mostra hotkey, marker di crop, intestazioni canali.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Canali&lt;/b&gt; &amp;mdash; ricorda FX per canale, ripristina ultima sessione, lega le impostazioni dei nuovi canali al primo.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Audio&lt;/b&gt; &amp;mdash; protezione earrape, FX personalizzati, audio sandbox, mostra pulsante export.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Log&lt;/b&gt; &amp;mdash; scrivi file di debug (vedi &lt;b&gt;menu Plugin &amp;rarr; Mostra log plugin&lt;/b&gt;).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Reset&lt;/b&gt; &amp;mdash; reset one-shot di canali, volumi, FX, file o impostazioni sandbox (con conferma).&lt;/li&gt;&lt;li&gt;&lt;b&gt;Tema&lt;/b&gt; &amp;mdash; tre colori + contrasto.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Lingua&lt;/b&gt; &amp;mdash; auto / en / it.&lt;/li&gt;&lt;/ul&gt;",

    "&lt;p&gt;The plugin checks for updates on startup. Run a manual check from &lt;b&gt;Plugins&lt;/b&gt; &amp;rarr; &lt;b&gt;Check for update&lt;/b&gt;. When a newer version exists it is downloaded from GitHub Releases for your platform (Windows / Linux / macOS) and a TS3 restart applies it.&lt;/p&gt;&lt;p&gt;From the &lt;b&gt;About&lt;/b&gt; dialog you can also open this guide and the &lt;b&gt;Version history&lt;/b&gt; &amp;mdash; the full change log of every documented release, browsable per-version on a split view.&lt;/p&gt;":
        "&lt;p&gt;Il plugin controlla gli aggiornamenti all&apos;avvio. Lancia un controllo manuale da &lt;b&gt;Plugin&lt;/b&gt; &amp;rarr; &lt;b&gt;Cerca aggiornamenti&lt;/b&gt;. Quando esiste una versione più recente viene scaricata dalle GitHub Releases per la tua piattaforma (Windows / Linux / macOS) e un riavvio di TS3 la applica.&lt;/p&gt;&lt;p&gt;Dalla finestra &lt;b&gt;Informazioni&lt;/b&gt; puoi anche aprire questa guida e la &lt;b&gt;Cronologia versioni&lt;/b&gt; &amp;mdash; il changelog completo di ogni release documentata, sfogliabile per versione in una vista divisa.&lt;/p&gt;",

    # --- multi-line tooltip strings (channel_sandbox_dialog / button_advanced_panel) ---
    "Play the sample back-to-front. Best on short cells; very long\nfiles use more memory.":
        "Riproduce il sample al contrario. Meglio su clip brevi; i file molto\nlunghi usano più memoria.",
    "Bring the cell to a consistent loudness so loud samples don&apos;t\ndrown quiet ones.":
        "Porta la clip a un volume costante così i sample forti non coprono\nquelli più deboli.",
    "DSP CPU used by this channel over the last second.\nHigh values mean a heavy effect is engaged.":
        "CPU DSP usata da questo canale nell&apos;ultimo secondo.\nValori alti significano un effetto pesante attivo.",
    "Classic: the original lightweight parametric HRTF.\nLeia: convolution with a measured HRTF dataset plus\nimage-source room reflections - correct front/back\nlocalisation and a far more convincing sense of space.\nIf the Leia data cannot load, playback falls back to\nClassic automatically.":
        "Classic: l&apos;HRTF parametrico leggero originale.\nLeia: convoluzione con dataset HRTF misurato più\nriflessioni image-source di stanza - localizzazione\nfront/back corretta e senso di spazio molto più convincente.\nSe i dati Leia non si caricano, la riproduzione torna\na Classic automaticamente.",
    "Image-source early reflections. They place the sound in a\nreal room - the single strongest &apos;out of the head&apos; cue.\nTurn off for a dry, anechoic placement.":
        "Riflessioni precoci image-source. Collocano il suono in una\nstanza reale - il singolo segnale &apos;fuori dalla testa&apos; più forte.\nDisattiva per un posizionamento secco e anecoico.",
    "Level of the direct (dry HRTF) path. 100 = full direct\nsound; lower values lean on the room reflections.":
        "Livello del percorso diretto (HRTF dry). 100 = suono\ndiretto pieno; valori più bassi si appoggiano alle riflessioni di stanza.",
    "Amount of room reflection blended in. 0 = pure direct,\nhigher = a wider, more enveloping space.":
        "Quantità di riflessione di stanza miscelata. 0 = solo diretto,\npiù alto = spazio più ampio e avvolgente.",
    "Roll a fresh random pitch offset every fire and on every\nloop. Keeps repeated triggers from sounding mechanical.":
        "Genera un nuovo offset di pitch casuale a ogni esecuzione e a ogni\nloop. Evita che i trigger ripetuti suonino meccanici.",
    "While this channel produces audio every other slot&apos;s\noutput is attenuated by the amount below. Smooth attack /\nrelease. Music channel + SFX channel pair: music dips\nunder the SFX and returns when it ends.":
        "Mentre questo canale produce audio, l&apos;uscita di ogni altro slot\nviene attenuata della quantità sotto. Attack / release smussati.\nCoppia canale musica + canale SFX: la musica si abbassa sotto\ngli SFX e torna su quando finiscono.",
}


def main() -> None:
    text = TS_PATH.read_text(encoding="utf-8")
    applied = 0
    skipped: list[str] = []

    for source, target in TRANSLATIONS.items():
        # Build a regex that matches the <message> block containing
        # this <source> and an unfinished translation. Replace just
        # the translation element with the IT text.
        escaped_source = re.escape(source)
        pattern = re.compile(
            r"(<source>" + escaped_source + r"</source>\s*)"
            r"<translation type=\"unfinished\">[^<]*</translation>",
            re.DOTALL,
        )
        new_text, n = pattern.subn(
            r"\1<translation>" + target.replace("\\", r"\\") + "</translation>",
            text,
        )
        if n == 0:
            skipped.append(source[:60])
        else:
            applied += n
            text = new_text

    TS_PATH.write_text(text, encoding="utf-8")
    print(f"Applied {applied} translations")
    if skipped:
        print(f"Skipped (no match) {len(skipped)}:")
        for s in skipped:
            print(f"  - {s}...")


if __name__ == "__main__":
    main()
